// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rzbydelamynswznlctxd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ6YnlkZWxhbXluc3d6bmxjdHhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4NDA3OTIsImV4cCI6MjA2MTQxNjc5Mn0.f331Rw6uwmU5D4faT8WRah0nixefexTp5hDvLc23peo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);